export const GIG_UPLOAD_REQUEST = "GIG_UPLOAD_REQUEST";
export const GIG_UPLOAD_SUCCESS = "GIG_UPLOAD_SUCCESS";
export const GIG_UPLOAD_FAIL = "GIG_UPLOAD_FAIL";

export const GIG_EDIT_REQUEST = "GIG_EDIT_REQUEST";
export const GIG_EDIT_SUCCESS = "GIG_EDIT_SUCCESS";
export const GIG_EDIT_FAIL = "GIG_EDIT_FAIL";

export const GIG_DELETE_REQUEST = "GIG_DELETE_REQUEST";
export const GIG_DELETE_SUCCESS = "GIG_DELETE_SUCCESS";
export const GIG_DELETE_FAIL = "GIG_DELETE_FAIL";

export const GIG_VIEW_REQUEST = "GIG_VIEW_REQUEST";
export const GIG_VIEW_SUCCESS = "GIG_VIEW_SUCCESS";
export const GIG_VIEW_FAIL = "GIG_VIEW_FAIL";
