export const HOME_PAGE_REQUEST = "HOME_PAGE_REQUEST";
export const HOME_PAGE_SUCCESS = "HOME_PAGE_SUCCESS";
export const HOME_PAGE_FAIL = "HOME_PAGE_FAIL";

export const HOME_PAGE_PAYLOAD_DELETE = "HOME_PAGE_PAYLOAD_DELETE";

export const REPORT_BUG_REQUEST = "REPORT_BUG_REQUEST";
export const REPORT_BUG_SUCCESS = "REPORT_BUG_SUCCESS";
export const REPORT_BUG_FAIL = "REPORT_BUG_FAIL";
