export const HOME_PAGE_REQUEST = "HOME_PAGE_REQUEST";
export const HOME_PAGE_SUCCESS = "HOME_PAGE_SUCCESS";
export const HOME_PAGE_FAIL = "HOME_PAGE_FAIL";

export const HOME_PAGE_PAYLOAD_DELETE = "HOME_PAGE_PAYLOAD_DELETE";

export const REPORT_BUG_REQUEST = "REPORT_BUG_REQUEST";
export const REPORT_BUG_SUCCESS = "REPORT_BUG_SUCCESS";
export const REPORT_BUG_FAIL = "REPORT_BUG_FAIL";

export const LOAD_MORE_GIGS_REQUEST = "LOAD_MORE_GIGS_REQUEST";
export const LOAD_MORE_GIGS_SUCCESS = "LOAD_MORE_GIGS_SUCCESS";
export const LOAD_MORE_GIGS_FAIL = "LOAD_MORE_GIGS_FAIL";
